#!/usr/bin/env bash
#
# Render the Homebrew formula for a released version.
#
#   render-formula.sh <version> <dir-of-sha256-files> > pinz.rb
#
# The checksum files are the ones the release workflow uploads next to each
# tarball, in `shasum -a 256` format: "<sum>  <filename>". Run by CI on every
# tag; runnable by hand against a directory of downloaded checksums when a
# release has to be repaired.
set -euo pipefail

version="${1:?usage: render-formula.sh <version> <sums-dir>}"
sums_dir="${2:?usage: render-formula.sh <version> <sums-dir>}"

# The sum for one target, by the tarball name the release workflow builds.
sum_for() {
  local target="$1"
  local file="${sums_dir}/pinz-${version}-${target}.tar.gz.sha256"
  if [ ! -f "$file" ]; then
    echo "missing checksum for ${target}: ${file}" >&2
    exit 1
  fi
  awk '{print $1}' "$file"
}

arm_mac="$(sum_for aarch64-apple-darwin)"
intel_mac="$(sum_for x86_64-apple-darwin)"
linux="$(sum_for x86_64-unknown-linux-gnu)"
base="https://github.com/Gaurgle/pinz/releases/download/v${version}"

cat <<FORMULA
# Generated by packaging/homebrew/render-formula.sh. Do not edit by hand:
# every release overwrites it with fresh URLs and checksums.
class Pinz < Formula
  desc "Spatial bulletin board in the terminal: post-it notes on a pannable, zoomable board"
  homepage "https://github.com/Gaurgle/pinz"
  version "${version}"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "${base}/pinz-${version}-aarch64-apple-darwin.tar.gz"
      sha256 "${arm_mac}"
    end
    on_intel do
      url "${base}/pinz-${version}-x86_64-apple-darwin.tar.gz"
      sha256 "${intel_mac}"
    end
  end

  on_linux do
    on_intel do
      url "${base}/pinz-${version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${linux}"
    end
  end

  def install
    bin.install "pinz"
  end

  test do
    # \`pinz version\` reaches the network to name the newest release, which a
    # test sandbox may not allow. \`help\` answers offline and still proves the
    # binary runs on this machine.
    assert_match "spatial bulletin board", shell_output("#{bin}/pinz help")
  end
end
FORMULA
